[platformio]

default_envs = esp07_rele


[env:esp07_base]

platform = espressif8266 @ 4.2.1
board = esp12e
board_build.flash_size = 4MB
board_build.ldscript = eagle.flash.4m2m.ld
framework = arduino

monitor_speed = 115200
upload_speed = 115200

lib_ldf_mode = deep+

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1

lib_deps =
    marcoschwartz/LiquidCrystal_I2C @ 1.1.4
    igorantolic/Ai Esp32 Rotary Encoder @ 1.6.0
    bblanchon/ArduinoJson @ 7.4.2
    ESP32Async/ESPAsyncWebServer @ 3.6.0
    ESP32Async/ESPAsyncTCP @ 2.0.0
    ayushsharma82/ElegantOTA @ 3.1.7


[env:esp07_rele]

extends = env:esp07_base

build_flags =
    ${env:esp07_base.build_flags}
    -DUSAR_RELE


[env:esp07_mosfet]

extends = env:esp07_base

build_flags =
    ${env:esp07_base.build_flags}
    -DUSAR_MOSFET


[env:native]

platform = native
test_build_src = no
build_flags = -I include
test_framework = unity
